import { Video, User } from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Ninja",
    avatar: "https://picsum.photos/seed/ninja/100/100",
    isLive: true,
    followers: 18000000,
  },
  {
    id: "u2",
    name: "Marques Brownlee",
    avatar: "https://picsum.photos/seed/mkbhd/100/100",
    isLive: false,
    followers: 16000000,
  },
  {
    id: "u3",
    name: "Pokimane",
    avatar: "https://picsum.photos/seed/poki/100/100",
    isLive: true,
    followers: 9000000,
  },
  {
    id: "u4",
    name: "MrBeast",
    avatar: "https://picsum.photos/seed/beast/100/100",
    isLive: false,
    followers: 200000000,
  },
];

export const MOCK_VIDEOS: Video[] = [
  {
    id: "v1",
    title: "I Built a Real Life Iron Man Suit!",
    thumbnail: "https://picsum.photos/seed/ironman/800/450",
    duration: "15:24",
    views: "12M",
    uploadedAt: "2 days ago",
    creator: MOCK_USERS[3],
    category: "Entertainment",
    description: "In this video, we spent $1,000,000 to build a functional Iron Man suit. Watch until the end to see it fly!",
    tags: ["tech", "engineering", "fun"],
  },
  {
    id: "v2",
    title: "LIVE: Valorant Ranked Grind with Friends",
    thumbnail: "https://picsum.photos/seed/valorant/800/450",
    duration: "LIVE",
    views: "45K",
    uploadedAt: "Started 2h ago",
    creator: MOCK_USERS[0],
    isLive: true,
    category: "Gaming",
    description: "Grinding to Radiant. Join the chat!",
    tags: ["valorant", "gaming", "live"],
  },
  {
    id: "v3",
    title: "iPhone 16 Pro Review: The Truth",
    thumbnail: "https://picsum.photos/seed/iphone/800/450",
    duration: "12:05",
    views: "5.4M",
    uploadedAt: "5 hours ago",
    creator: MOCK_USERS[1],
    category: "Technology",
    description: "The new iPhone is here. Is it worth the upgrade?",
    tags: ["apple", "iphone", "tech"],
  },
  {
    id: "v4",
    title: "Just Chatting & Reacting to Reddit",
    thumbnail: "https://picsum.photos/seed/chatting/800/450",
    duration: "LIVE",
    views: "12K",
    uploadedAt: "Started 1h ago",
    creator: MOCK_USERS[2],
    isLive: true,
    category: "Just Chatting",
    description: "Relaxing stream, come say hi!",
    tags: ["reddit", "react", "community"],
  },
  {
    id: "v5",
    title: "How to Master TypeScript in 10 Minutes",
    thumbnail: "https://picsum.photos/seed/typescript/800/450",
    duration: "10:00",
    views: "800K",
    uploadedAt: "1 week ago",
    creator: {
      id: "u5",
      name: "CodeMaster",
      avatar: "https://picsum.photos/seed/code/100/100",
    },
    category: "Education",
    description: "Learn the fundamentals of TypeScript quickly.",
    tags: ["programming", "typescript", "webdev"],
  },
  {
    id: "v6",
    title: "Epic Minecraft Survival Episode 100",
    thumbnail: "https://picsum.photos/seed/minecraft/800/450",
    duration: "45:00",
    views: "2.1M",
    uploadedAt: "3 days ago",
    creator: MOCK_USERS[3],
    category: "Gaming",
    description: "The finale of our survival series.",
    tags: ["minecraft", "gaming", "survival"],
  },
];

export const CATEGORIES = [
  "All",
  "Gaming",
  "Technology",
  "Music",
  "Live",
  "Education",
  "Entertainment",
  "Just Chatting",
  "Sports",
];
