'use client';

import { useEffect } from 'react';
import { usePrivy } from '@privy-io/react-auth';
import { supabase } from '@/lib/supabase';

/**
 * useAutoSaveWallet
 *
 * Runs after Privy login. If the authenticated user has an embedded EVM wallet
 * generated by Privy, saves its address to their Supabase profile automatically.
 *
 * This means creators get a payout address the moment they sign up — no manual
 * Settings configuration required.
 */
export function useAutoSaveWallet() {
    const { ready, authenticated, user } = usePrivy();

    useEffect(() => {
        if (!ready || !authenticated || !user) return;

        const embeddedEVM = user.linkedAccounts?.find(
            (a: any) => a.type === 'wallet' && a.walletClientType === 'privy'
        ) as any;

        if (!embeddedEVM?.address) return;
        const walletAddress: string = embeddedEVM.address;

        const save = async () => {
            const { data: { session } } = await supabase.auth.getSession();
            if (!session?.user?.id) return;

            // Only write if the wallet_address column is not yet set
            const { data: profile } = await supabase
                .from('profiles')
                .select('wallet_address')
                .eq('id', session.user.id)
                .single();

            if (profile?.wallet_address) return; // already set, don't overwrite

            await supabase
                .from('profiles')
                .update({ wallet_address: walletAddress })
                .eq('id', session.user.id);

            console.log('[VibeStream] Auto-saved Privy wallet:', walletAddress);
        };

        save();
    }, [ready, authenticated, user]);
}
